[package]
name = "bouncy-window-manager"
version = "0.1.0"
authors = ["expectocode <expectocode@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = "0.9.0"
